---
- hosts: routers
  tasks:
          - name: Configure packet forwarding
            lineinfile:
                    path: /etc/sysctl.conf
                    line: net.ipv4.ip_forward=1
                    insertafter: EOF
          - name: Apply sysctl config-file
            shell: sysctl -p
          - name: Install required pkg
            become: yes
            apt:
                    pkg:
                            - nginx
          - name: Configure iptables
            shell: iptables -t nat -A POSTROUTING -s 10.10.0.0/16 -o ens4 -j MASQUERADE
          
- hosts: nginx
  tasks:
          - name: Configure nginx-reverse proxy
            copy:
                    src: ./proxy.conf
                    dest: /etc/nginx/sites-enabled/default
                    mode: "0655"
          - name: nginx restarted
            become: yes
            service: 
                name: nginx
                state: restarted
- hosts: app1
  tasks:
          - name: Install nginx
            apt:
                    pkg:
                            - nginx
          - name: Configure a web-application on App1
            copy:
                    src: ./App1.conf
                    dest: /etc/nginx/sites-enabled/default
                    mode: "0655"
          - name: nginx restarted
            become: yes
            service:
                     name: nginx
                     state: restarted
          - name: Set Content 
            copy:
                     src: ./App1.html
                     dest: /var/www/html/index.html
                     mode: "0655"
- hosts: app2
  tasks:
         - name: Install nginx
           apt:
                   pkg:
                           - nginx
         - name: Configure a web-application on App2
           copy:
                   src: ./App2.conf
                   dest: /etc/nginx/sites-enabled/default
                   mode: "0655"
         - name: nginx restarted
           become: yes
           service: 
                name: nginx
                state: restarted
         - name:
           copy:
                   src: ./App2.html
                   dest: /var/www/html/index.html
                   mode: "0655"


